### ISSUE TITLE
Adding Dist folder ?

### ISSUE THREAD

**Issue by shirshak55** [wilburpowery/RoutesCached#1]
Otherwise I think we need compile manually inside vendor wilburypowery/route-cached using npm which will be erased on next update

```
file_get_contents(/Users/shirshak/xsadf/admin/vendor/wilburpowery/routes-cached/src/../dist/js/card.js): failed to open stream: No such file or directory 
```

**Comment by shirshak55** [comment]
also I think AreRoutesCached class should extend Illuminate\Routing\Controller; than App\Http\Controller .

It is due to fact many people don't use App\Http\Controller or move that file to another location

**Comment by wilburpowery** [comment]
Thanks for pointing this out @shirshak55. I'll fix this a do a new release.

**Comment by wilburpowery** [comment]
This got resolved and a new version was tagged. Thanks again @shirshak55!
